name: suda
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - opencv>=4.6.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tqdm>=4.62.0
  - pillow>=8.3.0
  - jupyter
  - jupyterlab
  - pip
  - pip:
    - mediapipe>=0.9.0
    - tensorboard>=2.8.0
    - plotly>=5.0.0
    - imageio>=2.15.0
    - librosa>=0.9.0
    - colorama>=0.4.0
    - rich>=12.0.0
    - PyYAML>=6.0